///////////////////////////////////////////////////////////////////////////
// MODULE: 1000-case Test Bench for the TSC CPU module
// Description:
//   Stresses the cpu module with 1000 deterministic, boundary-focused WWD
//   checks. The program is generated by tasks so each expected value is tied
//   to the exact executed instruction count, including jump-skipped regions.
///////////////////////////////////////////////////////////////////////////

`timescale 1ns/100ps
`define PERIOD1 100
`define READ_DELAY 30
`define STABLE_TIME 10
`define MEMORY_SIZE 8192
`define WORD_SIZE 16

module tb_cpu_1000();

  localparam TOTAL_CASES = 1000;
  localparam MAX_INST    = 20000;

  wire readM;
  wire [`WORD_SIZE-1:0] address;
  wire [`WORD_SIZE-1:0] data;
  reg inputReady;
  reg reset_n;
  reg clk;

  wire [`WORD_SIZE-1:0] num_inst;
  wire [`WORD_SIZE-1:0] output_port;

  reg [`WORD_SIZE-1:0] outputData;
  reg [`WORD_SIZE-1:0] memory [0:`MEMORY_SIZE-1];

  reg expected_valid [0:MAX_INST-1];
  reg [`WORD_SIZE-1:0] expected_value [0:MAX_INST-1];
  reg [`WORD_SIZE-1:0] expected_case_id [0:MAX_INST-1];

  integer pc;
  integer exec_count;
  integer case_count;
  integer done_count;
  integer fail_count;
  integer i;
  integer seed;
  integer rs_i;
  integer rt_i;
  integer rd_i;
  integer imm_i;
  integer jump_i;
  reg [`WORD_SIZE-1:0] model_rf [0:3];

  cpu UUT (readM, address, data, inputReady,
           reset_n, clk, num_inst, output_port);

  initial begin
    clk = 0;
    inputReady = 0;

    reset_n = 1;
    #(`PERIOD1/4) reset_n = 0;
    #`PERIOD1 reset_n = 1;
  end

  always #(`PERIOD1/2) clk = ~clk;

  assign data = readM ? outputData : `WORD_SIZE'bz;

  always begin
    outputData = `WORD_SIZE'bz;
    #`PERIOD1;
    forever begin
      wait (readM == 1);
      #`READ_DELAY;
      outputData = memory[address];
      inputReady = 1;
      #`STABLE_TIME;
      outputData = `WORD_SIZE'bz;
      inputReady = 0;
    end
  end

  function [`WORD_SIZE-1:0] enc_lhi;
    input [1:0] rt;
    input [7:0] imm;
    begin
      enc_lhi = {4'h6, 2'b00, rt, imm};
    end
  endfunction

  function [`WORD_SIZE-1:0] enc_adi;
    input [1:0] rs;
    input [1:0] rt;
    input [7:0] imm;
    begin
      enc_adi = {4'h4, rs, rt, imm};
    end
  endfunction

  function [`WORD_SIZE-1:0] enc_add;
    input [1:0] rs;
    input [1:0] rt;
    input [1:0] rd;
    begin
      enc_add = {4'hf, rs, rt, rd, 6'd0};
    end
  endfunction

  function [`WORD_SIZE-1:0] enc_wwd;
    input [1:0] rs;
    begin
      enc_wwd = {4'hf, rs, 2'b00, 2'b00, 6'd28};
    end
  endfunction

  function [`WORD_SIZE-1:0] enc_jmp;
    input [11:0] target;
    begin
      enc_jmp = {4'h9, target};
    end
  endfunction

  function [`WORD_SIZE-1:0] sx8;
    input [7:0] imm;
    begin
      sx8 = {{8{imm[7]}}, imm};
    end
  endfunction

  function [7:0] boundary_imm;
    input integer idx;
    begin
      case (idx)
        0:  boundary_imm = 8'h00;
        1:  boundary_imm = 8'h01;
        2:  boundary_imm = 8'h02;
        3:  boundary_imm = 8'h03;
        4:  boundary_imm = 8'h04;
        5:  boundary_imm = 8'h07;
        6:  boundary_imm = 8'h08;
        7:  boundary_imm = 8'h0f;
        8:  boundary_imm = 8'h10;
        9:  boundary_imm = 8'h1f;
        10: boundary_imm = 8'h20;
        11: boundary_imm = 8'h3f;
        12: boundary_imm = 8'h40;
        13: boundary_imm = 8'h7e;
        14: boundary_imm = 8'h7f;
        15: boundary_imm = 8'h80;
        16: boundary_imm = 8'h81;
        17: boundary_imm = 8'h82;
        18: boundary_imm = 8'h8f;
        19: boundary_imm = 8'h90;
        20: boundary_imm = 8'h9f;
        21: boundary_imm = 8'ha0;
        22: boundary_imm = 8'hbf;
        23: boundary_imm = 8'hc0;
        24: boundary_imm = 8'hdf;
        25: boundary_imm = 8'he0;
        26: boundary_imm = 8'hef;
        27: boundary_imm = 8'hf0;
        28: boundary_imm = 8'hf7;
        29: boundary_imm = 8'hf8;
        30: boundary_imm = 8'hfe;
        default: boundary_imm = 8'hff;
      endcase
    end
  endfunction

  function [`WORD_SIZE-1:0] seed_value;
    input integer seed_idx;
    input integer reg_idx;
    begin
      case ((seed_idx + reg_idx) % 8)
        0: seed_value = 16'h0000;
        1: seed_value = 16'h0001;
        2: seed_value = 16'h00ff;
        3: seed_value = 16'h0100;
        4: seed_value = 16'h7fff;
        5: seed_value = 16'h8000;
        6: seed_value = 16'hff00;
        default: seed_value = 16'hffff;
      endcase
    end
  endfunction

  task emit_exec;
    input [`WORD_SIZE-1:0] inst;
    begin
      memory[pc] = inst;
      pc = pc + 1;
      exec_count = exec_count + 1;
    end
  endtask

  task emit_lhi;
    input [1:0] rt;
    input [7:0] imm;
    begin
      emit_exec(enc_lhi(rt, imm));
      model_rf[rt] = {imm, 8'h00};
    end
  endtask

  task emit_adi;
    input [1:0] rs;
    input [1:0] rt;
    input [7:0] imm;
    begin
      emit_exec(enc_adi(rs, rt, imm));
      model_rf[rt] = model_rf[rs] + sx8(imm);
    end
  endtask

  task emit_add;
    input [1:0] rs;
    input [1:0] rt;
    input [1:0] rd;
    begin
      emit_exec(enc_add(rs, rt, rd));
      model_rf[rd] = model_rf[rs] + model_rf[rt];
    end
  endtask

  task emit_check;
    input [1:0] rs;
    input [`WORD_SIZE-1:0] expected;
    begin
      emit_exec(enc_wwd(rs));
      expected_valid[exec_count - 1] = 1'b1;
      expected_value[exec_count - 1] = expected;
      expected_case_id[exec_count - 1] = case_count + 1;
      case_count = case_count + 1;
    end
  endtask

  task set_reg;
    input [1:0] rt;
    input [`WORD_SIZE-1:0] value;
    reg [7:0] high_byte;
    reg [7:0] low_byte;
    begin
      high_byte = value[15:8];
      low_byte = value[7:0];
      if (low_byte < 8'h80) begin
        emit_lhi(rt, high_byte);
        emit_adi(rt, rt, low_byte);
      end
      else begin
        emit_lhi(rt, high_byte + 8'h01);
        emit_adi(rt, rt, low_byte);
      end
      model_rf[rt] = value;
    end
  endtask

  task emit_jump_forward;
    input integer skipped_words;
    integer target;
    integer j;
    begin
      target = pc + skipped_words + 1;
      emit_exec(enc_jmp(target[11:0]));
      for (j = 0; j < skipped_words; j = j + 1) begin
        memory[pc] = enc_wwd(j[1:0]);
        pc = pc + 1;
      end
    end
  endtask

  initial begin
    #`PERIOD1;

    pc = 0;
    exec_count = 0;
    case_count = 0;
    done_count = 0;
    fail_count = 0;

    for (i = 0; i < `MEMORY_SIZE; i = i + 1)
      memory[i] = enc_adi(2'd0, 2'd0, 8'h00);

    for (i = 0; i < MAX_INST; i = i + 1) begin
      expected_valid[i] = 1'b0;
      expected_value[i] = 16'hxxxx;
      expected_case_id[i] = 16'h0000;
    end

    for (i = 0; i < 4; i = i + 1)
      model_rf[i] = 16'h0000;

    // 128 checks: every register gets a sweep of immediate byte boundaries.
    for (rt_i = 0; rt_i < 4; rt_i = rt_i + 1) begin
      for (imm_i = 0; imm_i < 32; imm_i = imm_i + 1) begin
        emit_lhi(rt_i[1:0], boundary_imm(imm_i));
        emit_check(rt_i[1:0], model_rf[rt_i]);
      end
    end

    // 512 checks: signed ADI across source/destination aliases and edges.
    for (rs_i = 0; rs_i < 4; rs_i = rs_i + 1) begin
      for (seed = 0; seed < 8; seed = seed + 1) begin
        set_reg(rs_i[1:0], seed_value(seed, rs_i));
        for (imm_i = 0; imm_i < 16; imm_i = imm_i + 1) begin
          rt_i = (rs_i + seed + imm_i) % 4;
          emit_adi(rs_i[1:0], rt_i[1:0], boundary_imm(imm_i * 2));
          emit_check(rt_i[1:0], model_rf[rt_i]);
        end
      end
    end

    // 320 checks: ADD over all rs/rt/rd combinations with wraparound seeds.
    for (seed = 0; seed < 5; seed = seed + 1) begin
      for (i = 0; i < 4; i = i + 1)
        set_reg(i[1:0], seed_value(seed * 2, i));

      for (rs_i = 0; rs_i < 4; rs_i = rs_i + 1) begin
        for (rt_i = 0; rt_i < 4; rt_i = rt_i + 1) begin
          for (rd_i = 0; rd_i < 4; rd_i = rd_i + 1) begin
            emit_add(rs_i[1:0], rt_i[1:0], rd_i[1:0]);
            emit_check(rd_i[1:0], model_rf[rd_i]);
          end
        end
      end
    end

    // 40 checks: forward jumps, poisoned fall-through words, and dependency chains.
    for (jump_i = 0; jump_i < 4; jump_i = jump_i + 1) begin
      emit_jump_forward(3);
      set_reg(2'd0, seed_value(jump_i, 0));
      set_reg(2'd1, seed_value(jump_i + 3, 1));
      for (i = 0; i < 10; i = i + 1) begin
        rd_i = (i + jump_i) % 4;
        rs_i = (i + 1) % 4;
        rt_i = (i + 2) % 4;
        emit_add(rs_i[1:0], rt_i[1:0], rd_i[1:0]);
        emit_adi(rd_i[1:0], rd_i[1:0], boundary_imm(31 - i));
        emit_check(rd_i[1:0], model_rf[rd_i]);
      end
    end

    if (case_count != TOTAL_CASES) begin
      $display("TESTBENCH_GENERATION_FAIL generated=%0d expected=%0d", case_count, TOTAL_CASES);
      $finish;
    end
  end

  always @(posedge clk) begin
    if (num_inst < MAX_INST && expected_valid[num_inst]) begin
      done_count = done_count + 1;
      if (output_port === expected_value[num_inst]) begin
        $display("PASS case=%0d inst=%0d output=%0d", expected_case_id[num_inst], num_inst, output_port);
      end
      else begin
        fail_count = fail_count + 1;
        $display("FAIL case=%0d inst=%0d got=%0d expected=%0d",
                 expected_case_id[num_inst], num_inst, output_port, expected_value[num_inst]);
      end

      if (done_count == TOTAL_CASES) begin
        if (fail_count == 0)
          $display("ALL_PASS total=%0d", TOTAL_CASES);
        else
          $display("DONE_WITH_FAILURES total=%0d failures=%0d", TOTAL_CASES, fail_count);
        #`PERIOD1;
        $finish;
      end
    end
  end

  initial begin
    #(`PERIOD1 * MAX_INST);
    $display("TIMEOUT completed=%0d/%0d failures=%0d", done_count, TOTAL_CASES, fail_count);
    $finish;
  end

endmodule
